# Generated by Django 4.1.2 on 2022-12-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("technologies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("base_url", models.CharField(max_length=255)),
                ("repository", models.CharField(max_length=255)),
                (
                    "technologies",
                    models.ManyToManyField(
                        related_name="project", to="technologies.technologie"
                    ),
                ),
            ],
        ),
    ]
